name: composition_rendering
description: A tool for creating objects based on composition and painting on canvas.  It can be used in the base of the game engine.
version: 0.1.1
homepage: 'https://github.com/QiXi/composition_rendering'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.24.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0
