name: composition_rendering
description: A graphics engine for creating 2D games. Creating objects based on composition and painting on canvas.
version: 0.4.0
homepage: 'https://github.com/QiXi/composition_rendering'

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.24.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: '>=2.1.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.17.0
